output_dir: $SCRATCH/cosmoflow-benchmark/cosmoflow-19-06-17

data:
    name: cosmo
    data_dir: /project/projectdirs/m3363/www/cosmoUniverse_2019_02_4parE/dim128_cube_nT4
    n_train_files: 512
    n_valid_files: 256
    samples_per_file: 64
    sample_shape: [128, 128, 128, 4]
    batch_size: 8
    n_epochs: 32

model:
    name: cosmojan
    input_shape: [128, 128, 128, 4]
    target_size: 4
    dropout: 0.2

optimizer:
    name: Adadelta
    lr: 0.5

train:
    loss: mse
    metrics: ['mae']
