output_dir: $SCRATCH/cosmoflow-benchmark/cosmoflow-test

data:
    name: cosmo
    data_dir: /global/cscratch1/sd/sfarrell/cosmoflow-benchmark/data/cosmoUniverse_2019_02_4parE/dim128_cube_nT4
    n_train: 40960 # 640 files
    n_valid: 16384 # 256 files
    samples_per_file: 64
    shard_type: global
    sample_shape: [128, 128, 128, 4]
    batch_size: 1
    n_epochs: 64

model:
    name: configurable_cosmoflow
    input_shape: [128, 128, 128, 4]
    target_size: 4
    conv_sizes: [16, 16, 16, 16, 16]
    fc_sizes: [128, 64]
    dropout: 0.2

optimizer:
    name: Adadelta
    lr: 0.5
    lr_scaling: none

train:
    loss: mse
    metrics: ['mae']
    lr_schedule:
        16: 0.3
        32: 0.333
    early_stopping_patience: 4
