output_dir: $SCRATCH/cosmoflow-benchmark/results/cosmoflow-2020-03-12

data:
    name: cosmo
    data_dir: /global/cscratch1/sd/sfarrell/cosmoflow-benchmark/data/cosmoUniverse_2019_05_4parE_tf
    n_train: 131072
    n_valid: 32768
    sample_shape: [128, 128, 128, 4]
    batch_size: 4
    n_epochs: 64
    shard: True
    apply_log: True
    prefetch: 8

model:
    name: cosmoflow
    input_shape: [128, 128, 128, 4]
    target_size: 4
    conv_size: 32
    fc1_size: 128
    fc2_size: 64
    hidden_activation: LeakyReLU
    pooling_type: MaxPool3D
    dropout: 0.5

optimizer:
    name: SGD
    lr: 0.01
    momentum: 0.9
    lr_scaling: none

train:
    loss: mse
    metrics: ['mae']
    lr_schedule:
        16: 0.3
        32: 0.333
    early_stopping_patience: 8
