output_dir: $SCRATCH/cosmoflow-benchmark/cosmoflow-19-06-12

data:
    name: cosmo
    data_dir: /project/projectdirs/m3363/www/cosmoUniverse_2018_10_3parA/dim128_cube
    n_train_files: 3000
    n_valid_files: 1000
    samples_per_file: 16
    batch_size: 4
    n_epochs: 32

model:
    name: cosmoflow
    input_shape: [128, 128, 128, 1]
    target_size: 3
    dropout: 0.2

optimizer:
    name: Adadelta
    lr: 0.001

train:
    loss: mse
    metrics: ['mae']
