output_dir: $SCRATCH/cosmoflow-benchmark/results/cosmoflow-000

data:
    name: cosmo
    data_dir: /global/cscratch1/sd/sfarrell/cosmoflow-benchmark/data/cosmoUniverse_2019_05_4parE_tf
    n_train: 262144
    n_valid: 65536
    sample_shape: [128, 128, 128, 4]
    batch_size: 4
    n_epochs: 128
    shard: True
    apply_log: True
    prefetch: 4

model:
    name: cosmoflow
    input_shape: [128, 128, 128, 4]
    target_size: 4
    conv_size: 32
    fc1_size: 128
    fc2_size: 64
    hidden_activation: LeakyReLU
    pooling_type: MaxPool3D
    dropout: 0.5

optimizer:
    name: SGD
    momentum: 0.9

lr_schedule:
    base_lr: 0.01
    decay_schedule:
        32: 0.1
        64: 0.01

train:
    loss: mse
    metrics: ['mae']
    early_stopping_patience: 8
