output_dir: $SCRATCH/cosmoflow-benchmark/cosmoflow-v2-2019-10-24

data:
    #name: dummy
    #n_train: 512
    #n_valid: 512
    #target_shape: [4]
    name: cosmo
    data_dir: /global/cscratch1/sd/sfarrell/cosmoflow-benchmark/data/cosmoUniverse_2019_05_4parE_tf
    n_train: 65536 #131072
    n_train: 16384
    shard_type: global
    sample_shape: [128, 128, 128, 4]
    batch_size: 1
    n_epochs: 64

model:
    name: cosmoflow
    input_shape: [128, 128, 128, 4]
    target_size: 4
    dropout: 0.2

optimizer:
    name: Adadelta
    lr: 0.5
    lr_scaling: none

train:
    loss: mse
    metrics: ['mae']
    lr_schedule:
        16: 0.3
        32: 0.333
    early_stopping_patience: 4
