output_dir: $SCRATCH/cosmoflow-benchmark/cosmoflow-19-06-19

data:
    name: cosmo
    data_dir: /project/projectdirs/m3363/www/cosmoUniverse_2019_02_4parE/dim128_cube_nT4
    #data_dir: /global/cscratch1/sd/sfarrell/cosmoflow-benchmark/data/cosmoUniverse_2019_02_4parE/dim128_cube_nT4
    n_train_files: 640
    n_valid_files: 256
    samples_per_file: 64
    sample_shape: [128, 128, 128, 4]
    batch_size: 1
    n_epochs: 64

model:
    name: cosmoflow
    input_shape: [128, 128, 128, 4]
    target_size: 4
    dropout: 0.2

optimizer:
    name: Adadelta
    lr: 0.5
    lr_scaling: none

train:
    loss: mse
    metrics: ['mae']
    lr_schedule:
        - {start_epoch: 16, end_epoch: 32, multiplier: 0.3}
        - {start_epoch: 32, end_epoch: 64, multiplier: 0.1}
