output_dir: $SCRATCH/cosmoflow-benchmark/results/cosmoflow-19-10-24

data:
    name: cosmo
    #data_dir: $DW_PERSISTENT_STRIPED_cosmobb/cosmoUniverse_2019_02_4parE/dim128_cube_nT4
    data_dir: /global/cscratch1/sd/sfarrell/cosmoflow-benchmark/data/cosmoUniverse_2019_02_4parE/dim128_cube_nT4
    n_train: 40960 # 640 files
    n_valid: 16384 # 256 files
    samples_per_file: 64
    shard: True
    sample_shape: [128, 128, 128, 4]
    shuffle_buffer_size: 128
    batch_size: 1
    n_epochs: 64

model:
    name: cosmoflow_v1
    input_shape: [128, 128, 128, 4]
    target_size: 4
    dropout: 0.2

optimizer:
    name: Adadelta
    lr: 0.5
    lr_scaling: none

train:
    loss: mse
    metrics: ['mae']
    lr_schedule:
        16: 0.3
        32: 0.333
    early_stopping_patience: 4
